name: 'EAS Build'
description: 'Composite action to run eas build'

inputs:
  platform:
    description: 'platform'
    required: true
  profile:
    description: 'Build profile from eas.json'
    required: true
  projectRoot:
    description: 'Relative path to root of the EAS project'
    required: true
  expoToken:
    description: 'Expo token'
    required: true

outputs:
  build_id:
    description: "EAS Build ID"
    value: ${{ steps.build_start.outputs.build_id }}

runs:
  using: 'composite'
  steps:
    - name: Build start
      shell: bash
      id: build_start
      run: |
        BUILD_ID=$(eas build -p $PLATFORM --profile $EAS_BUILD_PROFILE --non-interactive --json --no-wait | jq -r ".[0].id")
        echo ::set-output name=build_id::"$BUILD_ID"
      working-directory: ${{ inputs.projectRoot }}
      env:
        EXPO_TOKEN: ${{ inputs.expoToken }}
        EAS_BUILD_PROFILE: ${{ inputs.profile }}
        PLATFORM: ${{ inputs.platform }}
        EAS_DANGEROUS_OVERRIDE_ANDROID_APPLICATION_ID: host.exp.exponent
