name: iOS Client - EAS Build

on:
  workflow_dispatch:
    inputs:
      buildType:
        required: true
        type: 'choice'
        description: 'buildType'
        options: 
          - versioned-client
          - unversioned-client
          - versioned-client-signed
  schedule:
    - cron: '20 5 * * 1,3,5' # 5:20 AM UTC time on every Monday, Wednesday and Friday
  pull_request:
    paths:
      - .github/workflows/client-ios-eas.yml
      - apps/eas-expo-go/**
      - ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - tools/src/client-build/**
      - tools/src/commands/ClientBuild.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
      - .ruby-version
      - yarn.lock
  push:
    branches: [main, sdk-*]
    paths:
      - .github/workflows/client-ios-eas.yml
      - apps/eas-expo-go/**
      - ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - tools/src/client-build/**
      - tools/src/commands/ClientBuild.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
      - .ruby-version
      - yarn.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: 🔓 Decrypt secrets if possible
        uses: ./.github/actions/expo-git-decrypt
        with:
          key: ${{ secrets.GIT_CRYPT_KEY_BASE64 }}
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-workspace: 'true'
          yarn-tools: 'true'
      - name: 🧶 Yarn install
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Install eas-cli
        run: npm install -g eas-cli
      - name: Build
        uses: ./.github/actions/eas-build-start
        id: build
        with:
          platform: 'ios'
          profile: ${{ github.event.inputs.buildType || 'unversioned-client' }}
          projectRoot: './apps/eas-expo-go'
          expoToken: ${{ secrets.EAS_BUILD_BOT_TOKEN }}
    outputs:
      build_id: ${{ steps.build.outputs.build_id }}
  check:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: 🧶 Yarn install
        run: yarn install --frozen-lockfile
      - name: Install eas-cli
        run: npm install -g eas-cli
      - name: Build
        uses: ./.github/actions/eas-build-check
        with:
          platform: 'ios'
          profile: ${{ github.event.inputs.buildType || 'unversioned-client' }}
          projectRoot: './apps/eas-expo-go'
          expoToken: ${{ secrets.EAS_BUILD_BOT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          build_id: ${{ needs.build.outputs.build_id }}
      - uses: LouisBrunner/checks-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Expo Go - test
          status: in_progress
